# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
variables:
  directory: cedrus-devops-poc
  serviceConnection: poc_test_connection
  appServiceName: cedrus-poc-ui

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    sourceFolder: 'build' 
    # Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

# - task: ArchiveFiles@2
#   displayName: 'Archive files'
#   inputs:
#     rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
#     includeRootFolder: false
#     # archiveType: zip
#     archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs: 
    pathtoPublish:  '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    # PathtoPublish: '$(build.artifactstagingdirectory)'

- task: AzureWebApp@1
  displayName: 'Deploy to App Service'
  inputs:
    azureSubscription: poc_test_connection
    appName: cedrus-poc-ui
    appType: webApp
    package:  '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    # package: '$(System.ArtifactsDirectory)'
